### ISSUE TITLE
ome-zarr source

### ISSUE THREAD

**Issue by manthey** [girder/large_image#1008]
We may want to integrate the ome-zarr library as a tile source.

**Comment by arjunrajlab** [comment]
@manthey I just spoke with the folks at the BioImage Archive:
https://www.ebi.ac.uk/bioimage-archive/
They were very interested in our work, and all their data (which is rapidly becoming the world's imaging data) is automatically transcoded into nice pyramidalized OME-zarr. I think it would be great to implement this as a source because then we could nicely interface with this huge repository of data.

They said they have worked with Matt McCormick at Kitware before.

**Comment by manthey** [comment]
Added in #1350.
