### ISSUE TITLE
Add support for more DICOMweb transfer syntaxes

### ISSUE THREAD

**Issue by psavery** [girder/large_image#1308]
See discussion [here](https://github.com/girder/large_image/pull/1303#discussion_r1330152068).

This may require making changes to [wsidicom](https://github.com/imi-bigpicture/wsidicom).

**Comment by psavery** [comment]
If [this issue](https://github.com/imi-bigpicture/wsidicom/issues/119) is fixed, it will largely fix this issue as well.

**Comment by psavery** [comment]
If we add the optional dependencies `imagecodecs` and `pylibjpeg-rle`, several more transfer syntaxes will be supported. The full list can be found [here](https://github.com/imi-bigpicture/wsidicom#limitations).

**Comment by manthey** [comment]
We can add `imagecodecs` as a dependency directly, since it has good cross-platform support.

For `pylibjpeg-rle`, it doesn't have binary wheels for python >= 3.11, which means that we can't install it on modern python without a rust compiler.  We can either add this with a version restriction (< 3.11, which means we'll need to update it when they release a newer wheel), or we add it as an extra requires and build our own linux wheels for it.  For the nonce, maybe just add it with a version restriction?

**Comment by psavery** [comment]
Pydicom's RLE decoder [only requires numpy to be present](https://github.com/pydicom/pydicom/blob/c5f756b70899bcbc0351809dab24bff5ea8c00d3/src/pydicom/pixel_data_handlers/rle_handler.py#L42-L48). I asked Erik if he would consider using that instead.
