### ISSUE TITLE
Move annotation code to its own plugin

### ISSUE THREAD

**Issue by brianhelba** [girder/large_image#155]
I propose that we eventually move the annotation code into its own plugin, which will then likely depend on `large_image`. Ideally, I think we'd probably keep both plugins in this repository, so they can share testing, bug tracker, etc. infrastructure, but we'll need to ensure that this works cleanly with the girder installation process, for both development and production.

This has the benefit on allowing users access to the tileserver functionality of `large_image`, without bringing in the extra endpoints and complexity of the annotation system.

**Comment by jbeezley** [comment]
I agree with this in principle.  One engineering problem we have to overcome is that we want to be able to render the annotations as well.  This requires some sort of support within the large_image `imageViewer` class.  We can add some sort of hook for this as I did in my PR [here](https://github.com/girder/large_image/pull/152/files#diff-09cb775a111926de61b96e3601613d1fR40), but the implementation for rendering will have to know details about  the annotation API.

The only solution I can think of at the moment to break them apart is to have the annotation plugin inject rendering methods into the large_image viewer classes.  A sticky point in doing that is related to https://github.com/girder/girder/pull/1742.  If an annotation plugin includes a module from the large_image plugin, it includes a *copy* of the module rather than a reference to it.  So any modifications made to these objects will only be visible inside the annotation plugin.

**Comment by manthey** [comment]
Done in #329.
