### ISSUE TITLE
MultiFileTileSource: pass dict on initialization

### ISSUE THREAD

**Issue by banesullivan-kobold** [girder/large_image#1638]
Instead of passing a file to `MultiFileTileSource` containing the YAML spec, could we implement a mechanism to pass a pre-built `dict`?

I find myself programmatically composing different images together and want to be able to easily create a tile source from that without writing out the YAML file.

This should be a straightforward change and I'm game to help if welcome

**Comment by manthey** [comment]
I think if you checked if the `path` was a dict and handled it adjacent to https://github.com/girder/large_image/blob/master/sources/multi/large_image_source_multi/__init__.py#L437-L444, validating it, it would work.  It might only work if `noCache=True` is passed, since the caching may choke on a dictionary (but I'd try it first).
