### ISSUE TITLE
Pin large_image dependency in source modules

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#708]
In the conda-forge recipes, I am pinning the large_image version based on the version of the source modules. Should we do the same here for the PyPI wheels? See https://github.com/conda-forge/staged-recipes/pull/17167#discussion_r762511623

This would help mitigate installing mismatched versions of large_image and source modules as well as simplify the upgrade process.

Just a thought and not really sure if this has actually posed an issue before

**Comment by manthey** [comment]
No one has reported this as an issue that I know of.  I'm always ambivalent about pinning -- it can help prevent mismatch, but it can also make it painful in certain development instances.  If done, it should be automated as part of the release script, since we don't want the pinning in the development environment.

**Comment by banesullivan** [comment]
Considering this hasn't been an issue for anyone thus far and it would require a bit of work to hook this up as a part of the release issue, I'd vote not to move forward with this.

I think it makes sense in the conda-forge recipes, but doing this for the PyPI wheels would be a burden
