### ISSUE TITLE
Memcached depend condition not working on Windows

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#723]
This condition should prevenr pylibmc from being installed on windows:

https://github.com/girder/large_image/blob/8e8deaae3b4165522a6894ea8d0cb5432d4839c2/setup.py#L13

However, it is not working:

```
pip install -r requirements.txt
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    CONDA_PKGS_DIR: C:\Users\runneradmin\conda_pkgs_dir
...
Collecting large-image[memcached]
  Downloading large_image-1.8.11-py3-none-any.whl (51 kB)
...
Collecting pylibmc>=1.5.1
  Downloading pylibmc-1.6.1.tar.gz (64 kB)
...
```

see Windows CI: https://github.com/banesullivan/localtileserver/runs/4500283500?check_suite_focus=true

I wonder if this is because the wheel is built on Linux and `pylibmc` is then listed as a dependency.

**Comment by manthey** [comment]
The correct way to specify this is entirely in the package string: `pylibmc>=1.5.1 ; platform_system != "Windows"` rather than as a conditional.  I had changed this four years ago, because it improved how things worked with the version of pip that was shipping with CentOS 7 and didn't seem to cause harm.  In reality, we need to change it back and require a recent-ish package manager.
