### ISSUE TITLE
Inconsistent handling of encoding

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#756]
Here is an example with this raster: https://download.osgeo.org/geotiff/samples/other/erdas_spnad83.tif from https://download.osgeo.org/geotiff/samples/other/

```py
import large_image
import json

tile_source = large_image.open(
    "/Users/bane/Downloads/erdas_spnad83.tif",
    projection='EPSG:3857',
    style=json.dumps({'nodata': 0})
)

thumb_data, mime_type = tile_source.getThumbnail(encoding="PNG")
with open('thumb.png', 'wb') as f:
    f.write(thumb_data)


tile_binary = tile_source.getTile(2183, 3274, 13)
with open('tile.png', 'wb') as f:
    f.write(tile_binary)

```

| Thumbnail | Tile |
|---|---|
| ![thumb](https://user-images.githubusercontent.com/22067021/149081484-d01f274a-2e86-40c0-953f-563c776b8420.png) |  ![tile](https://user-images.githubusercontent.com/22067021/149081519-20d71946-ae4f-468f-9723-3485ad153d98.png) |

Shown above, the thumbnail correctly hides the nodata value, but the tile generated from `getTile` does not - note the black border in the tile but not the thumbnail

----

Additionally, I noticed that nodata cannot handle string values, the following style fails `style=json.dumps({'nodata': '0'})` which is contrary to `min`/`max` and other numerical fields in the style

**Comment by manthey** [comment]
Isn't the tile in JPG format without transparency?  Set the encoding of the source to PNG and the tiles will show properly.

**Comment by banesullivan** [comment]
Oh, huh - thought tiles were PNG by default. I can confirm that passing `encoding="PNG"` to `large_image.open()` fixes this.

**Comment by banesullivan** [comment]
Though I am a bit concerned with the inconsistent behavior of  `getThumbnail()` and `getTile` with the `encoding` param.

- `getTile` requires you to have passed the `encoding` to `large_image.open()`
- `getThumbnail` only uses the encoding passed to it's call

This does not work:
```py
import large_image
import json

tile_source = large_image.open(
    "/Users/bane/Downloads/erdas_spnad83.tif",
    projection='EPSG:3857',
    style=json.dumps({'nodata': 0}),
    encoding="PNG"
)

# Produces JPEG
thumb_data, mime_type = tile_source.getThumbnail()
with open('thumb.png', 'wb') as f:
    f.write(thumb_data)

# Produces PNG
tile_binary = tile_source.getTile(2183, 3274, 13)
with open('tile.png', 'wb') as f:
    f.write(tile_binary)
```

vs.

```py
import large_image
import json

tile_source = large_image.open(
    "/Users/bane/Downloads/erdas_spnad83.tif",
    projection='EPSG:3857',
    style=json.dumps({'nodata': 0}),
)

# Produces PNG
thumb_data, mime_type = tile_source.getThumbnail(encoding='PNG')
with open('thumb.png', 'wb') as f:
    f.write(thumb_data)

# Produces JPEG
tile_binary = tile_source.getTile(2183, 3274, 13, encoding='PNG')
with open('tile.png', 'wb') as f:
    f.write(tile_binary)
```

**Comment by manthey** [comment]
The rational for encoding is that tiles are cached for the open tile source based on the sources parameters and the tile location.  If we add encoding as a *tile* parameter, then the cache has to check that as well, and now we have more complicated caching logic to test if the encoding is the same as the base encoding specified in the source or not, so this ends up being a more expensive call when trying to serve tiles efficiently.

For other methods, such as getThumbnail (and getAssociatedImage, getRegion), the calls are lower volume and therefore cache optimization is of less concern.  Moreover, one often wants a thumbnail in a different encoding than the tiles (and, for associated images, you might want them in their native encoding rather than reencoding them).

Removing encoding from getThumbnail and other endpoints would make it inefficient to get different formats from the same tile source (since we'd open the source for each encoding), so encoding should not be removed from those calls.

Adding encoding to getTile removes or complicates efficiency in tile requests.

Can we better document this somewhere rather than changing anything?

**Comment by banesullivan** [comment]
Thank you for clarifying this - makes a lot of sense now! 

I agree, nothing should be changed here, but perhaps this could be documented somewhere... I will have to think of where I might think would be most appropriate.

-----

This brings up a qualm I have with large_image more generally: there are too many `**kwargs` in function signatures. If `encoding` isn't a supported argument of `getTile()`, then passing it should error. But this is a bigger, separate issue that would require significant work to clean up all the `**kwargs` being passed around.
