### ISSUE TITLE
Not all GDAL sources are geospatial

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#805]
GDAL can handle a wide variety of image formats, and there is no requirement for the images of some formats to be geospatial. This line can lead to some wacky behavior when trying to handle tile serving or region extraction (wacky behavior downstream rather than in large image itself as I do `if source.geospatial: do stuff` in my code)

https://github.com/girder/large_image/blob/0ccb63390c463d3cd6beaf993a2e7dd14f352126/sources/gdal/large_image_source_gdal/__init__.py#L94

Could we change this to a `property` that does some sort of check to make sure the source is indeed geospatial? I have some non-geospatial images that are only readable by the GDAL source that I have shared as the `IHTest_202009_Path3_Step5_BBXSWIR_12deg_DistStA` file pair here: https://data.kitware.com/#user/5edea5859014a6d84eabf0f0/folder/61809f8b2fa25629b904edc7

**Comment by manthey** [comment]
This is actually the class property that says this class can handle geospatial data, so if the dataset is geospatial, prioritize this tile source over non-geospatial sources (and conversely, if the data isn't geospatial, prioritize non-geospatial sources over geospatial ones).  There is a utility function `tilesource.isGeospatial(<path>)`  that checks if the input is geospatial.

The tilesource has an optional property in its metadata `geospatial` that indicates if the specific source is geospatial, so your actual code could be `if source.getMetadata().get('geospatial'): do stuff`.

Clearly this isn't documented well enough, and perhaps it could be refactored so that class instances would have geospatial as a property for the current source.

**Comment by banesullivan** [comment]
Ah! Okay, this makes a bit more sense to me now. I'm wondering if we could refactor this a bit such that `geospatial` is an instance property that handles the logic that determines if `'geospatial'` in the metadata is true/false and let the current usage of the `geospatial` class attribute be renamed to a private-ish variable like `_geospatial_source` as this is only used internally?

**Comment by manthey** [comment]
Definitely.  The class property was done to be a general prioritization matching value, so the code that prioritization would need to be updated (and, realistically, only there).  I'd probably go for `_source_geospatial` so that if we ever do add other matching values they would all be prefixed via `_source_`.
