### ISSUE TITLE
WebP tiles and thumbnail

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#899]
Could WebP support be added for serving tiles and thumbnails? https://en.wikipedia.org/wiki/WebP

**Comment by manthey** [comment]
On linux, the GDAL wheels should already support this.

**Comment by banesullivan** [comment]
My understanding is the tile formats are handled in `_outputTile` from the `encoding` that the source was opened with:

https://github.com/girder/large_image/blob/e6cb017b95648c3b1688462b1ebe745b5718e820/large_image/tilesource/base.py#L1319

and the data given from GDAL is always a numpy array:

https://github.com/girder/large_image/blob/e6cb017b95648c3b1688462b1ebe745b5718e820/sources/gdal/large_image_source_gdal/__init__.py#L787

**Comment by manthey** [comment]
Actually, the only thing needed here (since PIL supports WEBP), is to add WEBP to https://github.com/girder/large_image/blob/master/large_image/constants.py#L39.  There are some minor things -- there is a list (elsewhere) which formats support transparency, quality settings have to be exposed, the Girder rest end points should enumerate the format.

Generally, each format could have a slight greater information about options somewhere to generalize output formats.
